name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: create build folder
      run: mkdir -p build && cd build
    - name: cmake
      run: cmake ..
    - name: make
      run: make
