name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: run build script
      run: ./build.sh
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.3
      with:
        # Artifact name
        name: streamfiler
        # A file, directory or wildcard pattern that describes what to upload
        path: build/streamfiler*

