name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: lukka/run-cmake@v2.5

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake .
    - name: make
      run: make
